s='CTATTATTTTAATTCCCTGACGCTCTATTTTAATATTTTATATTTTAGATATTTTATGATATTTTATATTTTAATTGTCATTATTTTATATTTTATATTTTAGGTCTATTTTATATTTTACTATTTTAAATATTTTATATTTTATGCCGGCGCCGAGCGGCCGATATTTTAGGTATTTTATATTTTATCTGTATTTTATATTTTATTTATTTTATAACGGGATGCCTATTTTATTATTTTATCTTCATATTTTATTATTTTACTATTTTAATTATTTTAGGCTATTTTACCTTATTTTAAGAGCTCTATTTTACAATCAAAGACTATTTTACACTAATTCCACAGTATTTTAAATATTTTATATTTTATATTTTACCTATTTTAAAAAGAATTATTTTACCGTATTTTACGTATTTTACATAGATATTTTATATTTTACCAATATTTTAGTTATTTTACTATTTTATATTTTACTGCCTTATTTTAATATTTTACTATTTTACTATTTTAATTTTTTATTTTAATTGTCAAGTATTTTATCTATTTTATATATTTTATATTTTACCTTATTTTACATATTTTATGCATATTTTATATTTTATATTTTATATTTTACTATTTTAGCATATTTTATCCCGTATTTTATATTTTATATTTTATTCTCGTCGTTATTTTACTATTTTATAATATTATTTTAATATTTTATGATCTGTTATTTTAATATTTTAAAATATTTTAATATTTTACTATTTTAGTATTTTATATTTTATATTTTACTTATCTATTTTATCTATTTTAACAGTATTTTAAGCATATCATATTTTAGTTATTTTACCTTCTGTATTTTAGCTTATTTTATA'
t='TATTTTATA'
start = 0
find = False
keep_list=[]


while not find:
    index = s.find(t,start)+1 #position start from 1, so that's why +1
    
    keep_list.append(str(index))
    start=index  

    if index == 0: #when t not found in parameter will return -1 but base on my code will return 0
        find = True
keep_list.remove('0') #remove not found index
print(' '.join(keep_list))
# print(type(keep_list[0])) index ap