Data= 'GGGTGTAAGGCGTTAGGCCGGGGTATATCTTGAACTACTCGTCAAGACCGCGACGCAGCCTTGAGAGATTGGTGCTGTGTACGACGGGATATGAGGTCGCCTTTCCAATATCCTTGTTATAGATTAACATGCACCACGGACCATAAGTCTGGACGTGAAGTGGAAGTGGCACTCAGTTACGATAATCTCTTCATCTCCTGTGCAATGGTGGTACAAGTCCTTTCCCGAAGCTCCAACTAATAACCTATGGGTCGTGTTCTCGATCATTGTGACTCCGTGGTCCACCGAACGCGAAGACAAAAAGCCAGACATTAGGTTTGAGACGCCTGGATAGGTCTGTAAAGCAGACGTGTCGGCTCAAGGGGGATGCCGAACGCCAGAGGAACCTGGTAGCGCCTGTATTCCTCTCAATTCGCCAAACTCAGGTTTCTCAACCAACATGGTGCAGTCATCGATATTACATGTGATTGCGCTTATGCCTTTGTATCCTTCGGCGAGTCGCTGTGGGGCAGCCTTCAGACGGGCAAGGTGAGCCGCCCTATCGCTACCTGAAGTACACACTCCAGTACATATCCGACACTTAACCACGTTCGAAAAGCAATACTTTCCCCGCCATAGATAAACCGTGTCATCCGACGTATTGTCGAGCTGCCAGCGTTAGATTGCGTATCATGCAAGTAGTTTGAATCTAGCCAATATTGATATGCCGAAGCCATGGCACCAAATCTCACCTTGGCTTTATCTCATGTTTCCTGGAGACGTAAAAAGACGTATGGGAGACGGGTAATACGATGGCGAAGTCTTGTAGGATTGAAAGTTCGTCGGGAATAGATCCCTAGTATTCGAGATAACTTCGCTAAAGGTTCGACTGCTGAGGGTATTTACTGCGAAACCCAACAGGCTACATGATCTTATCTGTGGGG' 
# print(Data[::-1])
New_list=[]
for k in list(Data):
    if k=='A':
        New_list.append('T')
    elif k == 'T':
        New_list.append('A')
    elif k == 'C':
        New_list.append('G')
    elif k == 'G':
        New_list.append('C')
New_string=''
print(New_string.join(New_list)[::-1])